#!/usr/bin/env bash
#installs Haproxy and setups load balancer with round robin algorithm
apt-get update
apt-get -y install haproxy
printf "\n frontend  alx "
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
    mode http
    balance roundrobin
    server 98227-web-01  54.146.61.68
    server 98227-web-02  3.85.175.175" >> /etc/haproxy/haproxy.cfg
service haproxy start
